export const BooksActionTypes = {
    TOGGLE_ADD_POPUP: 'TOGGLE_ADD_POPUP',
    ADD_NEW_BOOK: 'ADD_NEW_BOOK',
    DELETE_BOOK: 'DELETE_BOOK',
    TOGGLE_POPUP_EXPANDED: 'TOGGLE_POPUP_EXPANDED',
    EDIT_BOOK: 'EDIT_BOOK',
    CHANGE_FILTER: 'CHANGE_FILTER',
    SET_INITIAL_CATEGORY: 'SET_INITIAL_CATEGORY'
};