export const BooksActionTypes = {
    TOGGLE_POPUP_HIDDEN: 'TOGGLE_POPUP_HIDDEN',
    ADD_NEW_BOOK: 'ADD_NEW_BOOK',
    DELETE_BOOK: 'DELETE_BOOK',
    TOGGLE_POPUP_EXPANDED: 'TOGGLE_POPUP_EXPANDED',
    EDIT_BOOK: 'EDIT_BOOK'
};